#####################
# Build_n_Test Jobs #
#####################

centOS_mpich_mpi_gcc:
  extends:
    - .build_n_test
    - .nightly
  dependencies: [ mpich_legion ]
  variables:
    FLECSISP_RUNTIME: "mpi"
    FLECSISP_BUILD_TYPE: "Debug"
    FLECSISP_MPI_PROVIDER: "mpich"

centOS_mpich_mpi_gcc_release:
  extends: centOS_mpich_mpi_gcc
  variables:
    FLECSISP_BUILD_TYPE: "Release"

centOS_mpich_mpi_clang_release:
  extends: centOS_mpich_mpi_gcc_release

centOS_mpich_mpi_intel:
  extends: centOS_mpich_mpi_gcc
  allow_failure: true

centOS_mpich_mpi_intel_release:
  extends: centOS_mpich_mpi_intel
  variables:
    FLECSISP_BUILD_TYPE: "Release"

centOS_openmpi_mpi_gcc_release:
  extends: centOS_mpich_mpi_gcc
  dependencies: [ openmpi_legion ]
  variables:
    FLECSISP_BUILD_TYPE: "Release"
    FLECSISP_MPI_PROVIDER: "openmpi"

centOS_openmpi_mpi_clang_release:
  extends: centOS_openmpi_mpi_gcc_release

centOS_openmpi_mpi_clang:
  extends: centOS_openmpi_mpi_clang_release
  variables:
    FLECSISP_BUILD_TYPE: "Debug"

centOS_openmpi_mpi_intel_release:
  extends: centOS_openmpi_mpi_gcc_release
  allow_failure: true

centOS_openmpi_mpi_intel:
  extends: centOS_openmpi_mpi_intel_release
  variables:
    FLECSISP_BUILD_TYPE: "Debug"

